       
        ;ADDITION OF 2 NUMBERS
       MOV CX,0000      ;COUNT INITIALIZED WITH 0000H 
       MOV AX,0000AH    ;LOAD FIRST NUMBER INTO AX
       MOV BX,0FFFFH    ;LOAD SECOND NUMBER INTO BX
       ADD AX,BX        ;ADD AX AND BX AND STORE TO BX
       JNC STORE        ;IF CY=0 JUMP TO STORE
       INC CX           ;INCREASE COUNT BY 1
STORE: MOV DX,AX        ;STORE AX TO MEMORY
       MOV [3006],CX    ;STORE CX TO NEXT MEMORY LOCATION
       HLT              ;HALT




